In [1]:
import pandas as pd

In [2]:
from io import StringIO

In [3]:
csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

In [4]:
df = pd.read_csv(StringIO(csv_data))

In [5]:
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [6]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [7]:
df.dropna(axis = 0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [8]:
df.dropna(axis = 1)

      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

THESE FEATURES ARE TO REMOVE FEATURES WITH NAN VALUES

In [9]:
# only drop rows where all columns are NaN
# (returns the whole array here since we don't
# have a row with all values NaN)
df.dropna(how = 'all')

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [10]:
# drop rows that have fewer than 4 real values
df.dropna(thresh = 4)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [11]:
#only drop rows where NaN appear in specific columns (here: 'C')
df.dropna(subset=['C'])

      A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
import numpy as np

In [14]:
imr = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)

In [15]:
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [16]:
df.fillna(df.mean())

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.5  8.0
2  10.0  11.0  12.0  6.0

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2']])
df.columns = ['color', 'size', 'price', 'classlabel']

Nominal feature : colour
Ordinal feature : Size
Numerical feature : Price
Class labels

In [19]:
df

   color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [20]:
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}

In [37]:
df['size'] = df['size'].map(size_mapping)

In [22]:
df

   color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [23]:
# To convert the size back into strings we can define a reverse dictionary comprehension
inv_size_mapping = {v: k for k, v in size_mapping.items()}

In [24]:
df['size'] = df['size'].map(inv_size_mapping)

In [25]:
df

   color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [26]:
# Since a lot of ML algorithms require class labels to be numbers , hence we convert them. Since they are not ordinal thus can be converted using enumerate

In [27]:
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}

In [28]:
class_mapping

{'class1': 0, 'class2': 1}

In [29]:
df['classlabel'] = df['classlabel'].map(class_mapping)

In [30]:
df

   color size  price  classlabel
0  green    M   10.1           1
1    red    L   13.5           0
2   blue   XL   15.3           1

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y

array([1, 0, 1])

In [33]:
from sklearn.preprocessing import OneHotEncoder
X = df[['color','size','price']].values
color_ohe = OneHotEncoder()
color_ohe.fit_transform(X[:,0].reshape(-1,1)).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [35]:
from sklearn.compose import ColumnTransformer

In [38]:
X = df[['color','size', 'price']].values
c_transf = ColumnTransformer([('onehot', OneHotEncoder(), [0]),('nothing','passthrough',[1,2])])
c_transf.fit_transform(X).astype(float)

array([[ 0. ,  1. ,  0. ,  1. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  3. , 15.3]])